name: Deploy to VPS

on:
  push:
    branches:
      - main
      - idealab_v5
      - v5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/Idea-lab
            git pull
            docker compose down
            docker compose up --build -d
